### ISSUE TITLE
Set up Cookie cutter

### ISSUE THREAD

**Issue by peterhollender** [OpenwaterHealth/OpenLIFU-3DRegistration#1]
@ebrahimebrahim, @KedarOW will be using this repository for his automated mesh-registration transducer localization code, which will be Python-based, and likely use some VTK tools. This work will be, once complete, pulled into the openlifu project to process meshes imported form the android app, but it may be generic enough to stay as a standalone project. Either way, can we set up all of the scientific-python cookie cutter stuff we did for OpenLIFU-Python?

**Comment by ebrahimebrahim** [comment]
Yes, this will be much easier than openlifu since we're not adapting an existing codebase.

What should be the name of the python package? The thing that goes into

```py
import thing
```

and/or

```sh
pip install thing
```

**Comment by peterhollender** [comment]
can it be `openlifu-registration` or is that like a variant or sub-project of `openlifu`?

**Comment by ebrahimebrahim** [comment]
No that seems like a great name. I'll go ahead and make a PR with that.

**Comment by ebrahimebrahim** [comment]
Ah actually, that cannot be the name when you `import` -- the hyphen would become an underscore.

That's kind of a long import name `openlifu_registration` but I'll go ahead with it and we can change it if we come up with something better. Long can be okay still

**Comment by ebrahimebrahim** [comment]
I am putting Kedar as the author

**Comment by ebrahimebrahim** [comment]
Closed via #3
